### ISSUE TITLE
TWN3 min-cycles is wrong

### ISSUE THREAD

**Issue by jbzdarkid** [ExapunksBacardi/ExapunksRecords#3]
https://github.com/ExapunksBacardi/ExapunksRecords/blob/master/TWN3/9%7C12%7C4
This says `GRAB 200` which does not exist in this puzzle.

**Comment by BenjaminMidtvedt** [comment]
What is the file number?

**Comment by jbzdarkid** [comment]
According to the other solutions, there is no second file.

**Comment by BenjaminMidtvedt** [comment]
Old solution was a TWN2 solution. Created pull-request for twn3 record
